"""Constants for the ROBIN rl algorithms package."""

# TODO: Comments
TRAINER_SEED_RANK_MULTIPLIER = 1000
EVALUATOR_SEED_RANK_MULTIPLIER = 100_000

HIDDEN_SIZE = 256
LOG_STD_MAX = 2
LOG_STD_MIN = -20

IS_COOPERATIVE = {
    'maddpg': False,
    'matd3': False,
    'rache': False,
    'gaac': False
}

IS_GRAPH_BASED = {
    'maddpg': False,
    'matd3': False,
    'rache': True,
    'gaac': False
}

BASIC_FEATURES = 6
CATEGORICAL_BASIC_FEATURES = 5
CATEGORICAL_PER_MARKET_SEAT = 3
CONTINUOUS_PER_MARKET_SEAT = 2
FEATURES_PER_MARKET_SEAT = CATEGORICAL_PER_MARKET_SEAT + CONTINUOUS_PER_MARKET_SEAT
NUM_RELATIONS = 3

DEFAULT_EMBEDDING_DIM = 128
DEFAULT_HIDDEN_DIM = 128
DEFAULT_NUM_LAYERS = 2
DEFAULT_DROPOUT = 0.1
DEFAULT_CATEGORICAL_EMBEDDING_DIM = 4
DEFAULT_CONTINUOUS_INPUT_FEATURES = 2
DEFAULT_CONTINUOUS_HIDDEN_DIM = 128
DEFAULT_CONTINUOUS_OUTPUT_DIM = 128
DEFAULT_EMBEDDING_TOTAL_DIM = 64
