"""Constants for the ROBIN rl package."""

import numpy as np

# TODO: Comments
ACTION_FACTOR = 5
LOW_ACTION = -1
HIGH_ACTION = 1
NUMBER_ACTIONS = 11
START_ACTION = -5

LOW_PRICE = 0
HIGH_PRICE = np.inf

CLIP_MAX = 10.0

LOG_DIR = 'models'

FLATTENED_PRICE_POSITION = 4
FLATTENED_TICKETS_SOLD_POSITION = 6
FLATTENED_PROFIT_POSITION = 7

NODE_FEATURE_PROFIT_POSITION = 5
